version: "3.1"

services:
  db:
    build: ./db
    env_file: .env
    container_name: mongo-test
    restart: always
    volumes:
      - ${MONGO_DB_FOLDER}:/data/db
    ports:
      - "${MONGO_DB_PORT}:27017"
